import { Inter } from "next/font/google";
import "./globals.css";
import "./assets/css/animate.min.css"
import "./assets/css/bootstrap.min.css"
import "./assets/css/font-awesome-pro.min.css"
import "./assets/css/flaticon_gerold.css"
import "./assets/css/nice-select.css"
import "./assets/css/backToTop.css"
import "./assets/css/owl.carousel.min.css"
import "./assets/css/odometer-theme-default.css"
import "./assets/css/magnific-popup.css"
import "./assets/css/main.css"
import Head from "next/head";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <Script src="./assets/js/jquery.min.js" strategy="lazyOnload"/>
    <Script src="./assets/js/bootstrap.bundle.min.js" strategy="lazyOnload"/>
    <Script src="./assets/js/nice-select.min.js" strategy="lazyOnload"/>
    <Script src="./assets/js/backToTop.js" strategy="lazyOnload"/>
    <Script src="./assets/js/smooth-scroll.js" strategy="lazyOnload"/>
    <Script src="./assets/js/appear.min.js" strategy="lazyOnload"/>
    <Script src="./assets/js/wow.min.js" strategy="lazyOnload"/>
    <Script src="./assets/js/gsap.min.js" strategy="lazyOnload"/>
    <Script src="./assets/js/one-page-nav.js" strategy="lazyOnload"/>
    <Script src="./assets/js/lightcase.js" strategy="lazyOnload"/>
    <Script src="./assets/js/owl.carousel.min.js" strategy="lazyOnload"/>
    <Script src="./assets/js/isotope.pkgd.min.js" strategy="lazyOnload"/>
    <Script src="./assets/js/odometer.min.js" strategy="lazyOnload"/>
    <Script src="./assets/js/magnific-popup.js" strategy="lazyOnload"/>

    {/* <Script src="./assets/js/main.js" strategy="lazyOnload"/> */}
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
